// <auto-generated />
using CURDUsingAPIEx.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CURDUsingAPIEx.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20240411083631_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CURDUsingAPIEx.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<string>("MfgName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            MfgName = "Intex",
                            Price = 410m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductID = 2L,
                            MfgName = "Logitech",
                            Price = 410m,
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            ProductID = 3L,
                            MfgName = "LG",
                            Price = 4100m,
                            ProductName = "Monitor"
                        },
                        new
                        {
                            ProductID = 4L,
                            MfgName = "Renolds",
                            Price = 50m,
                            ProductName = "Marker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
