// <auto-generated />
using DataAPIContentNegotiationEx.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAPIContentNegotiationEx.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAPIContentNegotiationEx.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<string>("MfgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            MfgName = "Intex",
                            Price = 550m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductID = 2L,
                            MfgName = "Dell",
                            Price = 850m,
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            ProductID = 3L,
                            MfgName = "Benq",
                            Price = 6750m,
                            ProductName = "Monitor"
                        },
                        new
                        {
                            ProductID = 4L,
                            MfgName = "HP",
                            Price = 650m,
                            ProductName = "Pen Drive"
                        },
                        new
                        {
                            ProductID = 5L,
                            MfgName = "Renolds",
                            Price = 55m,
                            ProductName = "Marker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
